### ISSUE TITLE
Change target with arrow

### ISSUE THREAD

**Issue by mukhammad-amin** [uzbekvoice/new_website#120]
![image](https://user-images.githubusercontent.com/76046223/204514027-79677399-5fca-499a-8638-e4dff3433f6f.png)

I'll provide a jpg photo

**Comment by mukhammad-amin** [comment]
![archer3](https://user-images.githubusercontent.com/76046223/204525497-77f08ac6-859c-4108-be04-dcc1f1fa47dc.png)

**Comment by javohirdev** [comment]
completed
