### ISSUE TITLE
Changing ru lang version family font

### ISSUE THREAD

**Issue by mukhammad-amin** [uzbekvoice/new_website#124]
We need as many as possible font family versions that are suitable for all languages on our website

**Comment by ramildeve1oper** [comment]
shuni ko'ringlar, boshqa variant bo'lsa ham izlab ko'ramiz.

![1 1](https://user-images.githubusercontent.com/89657343/206749485-f7840368-ea45-4f6f-955a-36cb97ee95cf.PNG)





![1 2](https://user-images.githubusercontent.com/89657343/206749526-ea2f6e91-5a8e-49a4-be0b-559e62968120.png)





before

![1 12](https://user-images.githubusercontent.com/89657343/206749587-f59bc93d-cfb2-4e4b-8ed5-aa8ff16f24dc.PNG)





after

![1 11](https://user-images.githubusercontent.com/89657343/206749687-913c8272-b5c0-45fe-b349-707e67d8daf3.PNG)

**Comment by ramiljs** [comment]
> [](https://uzbekvoiceapp.vercel.app/)

ok

**Comment by ramiljs** [comment]
> @ramiljs Zo'r, testoviy serverga deploy qiling mana shunga https://uzbekvoiceapp.vercel.app/
> 
> @Abulfayz05 Ramil akaga dostup bering

ok

**Comment by mukhammad-amin** [comment]
> > @ramiljs Zo'r, testoviy serverga deploy qiling mana shunga https://uzbekvoiceapp.vercel.app/
> > @Abulfayz05 Ramil akaga dostup bering
> 
> ok

Menimcha shu variant yaxshi chiqdi

**Comment by ramiljs** [comment]
> productionga chiqaring @ramiljs

push qildim

**Comment by ramiljs** [comment]
> productionga chiqaring @ramiljs

@Abulfayz05 akaga push qilib qo'ygandim, aka prod ga push qilib yuboring

**Comment by mukhammad-amin** [comment]
@javascriptoramil Ramil aka, bu issueda Ru tiliga olganda, ushbu fontni ishlatsak bo'ladi, lekin uz en versiyalarida o'zgarib ketmash kerak

**Comment by mukhammad-amin** [comment]
done by @ramiljs
